services:
  - type: web
    name: blackhawk-scraper
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=10000
    autoDeploy: true
